/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nowe.presentacion;

import com.nowe.modelo.CDT;
import com.nowe.persistencia.AccesoCuentasBancarias;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author agarm
 */
public class GestionCDT extends javax.swing.JFrame {

    //Atributos
//    private AccesoCuentasBancarias acb1 = new AccesoCuentasBancarias();
    private int datoNumerico;

    /**
     * Creates new form GestionCDT
     */
    public GestionCDT() {
        initComponents();
        groupAcciones.add(chkCrearCDT);
        groupAcciones.add(chkCerrarCDT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAcciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chkCrearCDT = new javax.swing.JRadioButton();
        chkCerrarCDT = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCDT = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de CDT");

        chkCrearCDT.setText("Crear un CDT");
        chkCrearCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrearCDTActionPerformed(evt);
            }
        });

        chkCerrarCDT.setText("Cerrar un CDT");
        chkCerrarCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCerrarCDTActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta:");

        txtCuenta.setBorder(null);
        txtCuenta.setEnabled(false);
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        jLabel3.setText("Interés:");

        txtInteres.setBorder(null);
        txtInteres.setEnabled(false);

        jLabel4.setText("Monto:");

        txtMonto.setBorder(null);
        txtMonto.setEnabled(false);

        jLabel5.setText("CDT:");

        txtCDT.setBorder(null);
        txtCDT.setEnabled(false);

        btnAccion.setText("Realizar la acción");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        mensajeError.setBackground(new java.awt.Color(255, 255, 255));
        mensajeError.setForeground(new java.awt.Color(255, 0, 51));
        mensajeError.setToolTipText("");
        mensajeError.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCrearCDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkCerrarCDT)
                        .addGap(152, 152, 152))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtInteres))))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(txtCDT, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnAccion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCrearCDT)
                    .addComponent(chkCerrarCDT))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAccion)
                .addGap(27, 27, 27)
                .addComponent(mensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // 1. Identificar si es la acción de crear un CDT
        //0. Definir variables
        mensajeError.setText("");
        AccesoCuentasBancarias acb1 = new AccesoCuentasBancarias();

        if (chkCrearCDT.isSelected()) {
            int cuenta;
            double interes, monto;
            CDT inversion;
            boolean exito;

            //1.1 Recoger los datos de los controles
            try {
                cuenta = Integer.parseInt(txtCuenta.getText());
                interes = Double.parseDouble(txtInteres.getText());
                monto = Double.parseDouble(txtMonto.getText());

                //1.2 Instanciar un objeto CDT
                inversion = new CDT(cuenta, interes, monto);

                //1.3 LLamar a creación del CDT
                exito = acb1.crearInversion(inversion);
                txtCuenta.setText("");
                txtInteres.setText("");
                txtMonto.setText("");
                if (exito) {
                    mensajeError.setText("Se ha realizado el alta de su CDT correctamente");
                } else {
                    mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");
                mensajeError.setText(mensajeError.getText() + "\n" + ex.toString());
            } catch (NumberFormatException ex) {
                mensajeError.setText("Los datos deben ser numéricos");
            }

        }

        // 2. Identificar si es la acción de eliminar un CDT
        if (chkCerrarCDT.isSelected()) {
            //1. Declarar variables
            int CDT;
            boolean exito;
            try {
                //2. Recoger los datos de los controles
                CDT = Integer.parseInt(txtCDT.getText());
                //3. Llamar al método correspondiente para cerrarla
                exito = acb1.cerrarInversion(CDT);
                txtCDT.setText("");
                if (exito) {
                    mensajeError.setText("Se ha realizado el cierre de su CDT correctamente");
                } else {
                    mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                mensajeError.setText("Se ha producido un error en la base de datos, \nno se realizó la acción correctamente");
            } catch (NumberFormatException ex) {
                mensajeError.setText("Los datos deben ser numéricos");
            }

        }

//        if (chkCrearCDT.isSelected()) {
//            verificarNumero();
//            verificaVacio();
//            try {
//              // datoNumerico no, instanciar CDT porque crearInversion(pide objeto CDT)
//                txtCDT.setText(Double.toString(c1.crearInversion(datoNumerico))); //esto está mal, hay que modificar el parametro
//            } catch (ClassNotFoundException | SQLException ex) {
//                taMensajeError.setText(ex.toString());
//            }
//        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void chkCerrarCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCerrarCDTActionPerformed
        //Habilitar el control txtCDT
        //Deshabilitar los demás y limpiarlos
//        if (chkCerrarCDT.isSelected()) {
        txtCDT.setEnabled(true);
        txtCuenta.setEnabled(false);
        txtInteres.setEnabled(false);
        txtMonto.setEnabled(false);
//            txtCDT.setText("");
        txtCuenta.setText("");
        txtInteres.setText("");
        txtMonto.setText("");
        mensajeError.setText("");
//        }

    }//GEN-LAST:event_chkCerrarCDTActionPerformed

    private void chkCrearCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrearCDTActionPerformed
        //Habilitar los controles txtCuenta, txtInteres, txtMonto
        //Deshabilitar el control CDT y limpiarlo
//        if (chkCrearCDT.isSelected()) {
        txtCDT.setEnabled(false);
        txtCuenta.setEnabled(true);
        txtInteres.setEnabled(true);
        txtMonto.setEnabled(true);
        txtCDT.setText("");
//            txtCuenta.setText("");
//            txtInteres.setText("");
//            txtMonto.setText("");
        mensajeError.setText("");
//        }
    }//GEN-LAST:event_chkCrearCDTActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed
    private void verificarNumero() {
        //1. Recoger el dato de la caja de texto
        String datoTexto1 = txtCDT.getText();
        String datoTexto2 = txtCuenta.getText();
        String datoTexto3 = txtInteres.getText();
        String datoTexto4 = txtMonto.getText();

        //2. Si se puede convertir a entero
        try {
            datoNumerico = Integer.parseInt(datoTexto1);
            datoNumerico = Integer.parseInt(datoTexto2);
            datoNumerico = Integer.parseInt(datoTexto3);
            datoNumerico = Integer.parseInt(datoTexto4);
        } catch (Exception ex) {
            mensajeError.setText("El dato tiene que ser numérico");
            mensajeError.setText(ex.toString());
        }
    }

    private void verificaVacio() {
        //1. Recoger el dato de la caja de texto
        String datoTexto1 = txtCDT.getText();
        String datoTexto2 = txtCuenta.getText();
        String datoTexto3 = txtInteres.getText();
        String datoTexto4 = txtMonto.getText();
        if (datoTexto1.equals("") || datoTexto2.equals("") || datoTexto3.equals("") || datoTexto4.equals("")) {
            mensajeError.setText("El dato tiene que ser numérico");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JRadioButton chkCerrarCDT;
    private javax.swing.JRadioButton chkCrearCDT;
    private javax.swing.ButtonGroup groupAcciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JTextField txtCDT;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
