/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nowe.presentacion;

import com.nowe.persistencia.AccesoCuentasBancarias;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author agarm
 */
public class Menu_Principal_VariosBotones extends javax.swing.JFrame {

    //Atributos
    private AccesoCuentasBancarias c1 = new AccesoCuentasBancarias();
    private int datoNumerico;

    /**
     * Creates new form NewJFrame
     */
    public Menu_Principal_VariosBotones() {
        initComponents();
        buttonGroup1.add(chkSCuenta);
        buttonGroup1.add(chkSCDT);
        buttonGroup1.add(chkSCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblEtiqueta1 = new javax.swing.JLabel();
        chkSCuenta = new javax.swing.JRadioButton();
        chkSCDT = new javax.swing.JRadioButton();
        chkSCliente = new javax.swing.JRadioButton();
        lblConcepto = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        btnCSaldo = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensajeError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEtiqueta1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEtiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEtiqueta1.setText("Diferentes tipos de consultas");

        chkSCuenta.setText("Saldo cuenta");
        chkSCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSCuentaActionPerformed(evt);
            }
        });

        chkSCDT.setText("Saldo CDT");
        chkSCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSCDTActionPerformed(evt);
            }
        });

        chkSCliente.setText("Saldo cliente");
        chkSCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSClienteActionPerformed(evt);
            }
        });

        dato.setBackground(new java.awt.Color(255, 255, 255));
        dato.setEnabled(false);

        btnCSaldo.setText("Consultar saldo");
        btnCSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSaldoActionPerformed(evt);
            }
        });

        txtSaldo.setEditable(false);

        taMensajeError.setEditable(false);
        taMensajeError.setColumns(20);
        taMensajeError.setRows(5);
        jScrollPane1.setViewportView(taMensajeError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEtiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(txtSaldo)
                    .addComponent(btnCSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSCDT)
                            .addComponent(chkSCuenta)
                            .addComponent(chkSCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblEtiqueta1)
                .addGap(32, 32, 32)
                .addComponent(chkSCuenta)
                .addGap(18, 18, 18)
                .addComponent(chkSCDT)
                .addGap(18, 18, 18)
                .addComponent(chkSCliente)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnCSaldo)
                .addGap(29, 29, 29)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSCuentaActionPerformed
        // TODO add your handling code here:
        if (chkSCuenta.isSelected()) {
//            System.out.println("Se ha seleccionado la opción de saldo cuenta");
            lblConcepto.setText("Cuenta: ");
            dato.setText("");
            taMensajeError.setText("");
            txtSaldo.setText("");
             dato.setEnabled(true);
        } else {
            System.out.println("Se ha deseleccionado la opción de saldo cuenta");
        }

    }//GEN-LAST:event_chkSCuentaActionPerformed

    private void chkSCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSCDTActionPerformed
        // TODO add your handling code here:
        if (chkSCDT.isSelected()) {
//            System.out.println("Se ha seleccionado la opción de saldo CDT");
            lblConcepto.setText("CDT: ");
            dato.setText("");
            taMensajeError.setText("");
            txtSaldo.setText("");
             dato.setEnabled(true);
        } else {
            System.out.println("Se ha deseleccionado la opción de saldo CDT");
        }

    }//GEN-LAST:event_chkSCDTActionPerformed

    private void chkSClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSClienteActionPerformed
        // TODO add your handling code here:
        if (chkSCliente.isSelected()) {
//            System.out.println("Se ha seleccionado la opción de saldo del cliente");
            lblConcepto.setText("NIF: ");
            dato.setText("");
            taMensajeError.setText("");
            txtSaldo.setText("");
             dato.setEnabled(true);
        } else {
            System.out.println("Se ha deseleccionado la opción de saldo del cliente");
        }

    }//GEN-LAST:event_chkSClienteActionPerformed
    private void verificarNumero() {
        //1. Recoger el dato de la caja de texto
        String datoTexto = dato.getText();

        //2. Si se puede convertir a entero
        try {
            datoNumerico = Integer.parseInt(datoTexto);
        } catch (Exception ex) {
            taMensajeError.setText("El dato tiene que ser numérico");
            taMensajeError.setText(ex.toString());

        }
    }

    private void verificaVacio() {
        //1. Recoger el dato de la caja de texto
        String datoTexto = dato.getText();
        if (datoTexto.equals("")) {
            taMensajeError.setText("El dato tiene que ser numérico");
        }
    }
    private void btnCSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSaldoActionPerformed
        // Dependiendo del radio botón seleccionado es el saldo que va a consultar
        if (chkSCuenta.isSelected()) {
//            // 1. Recoger los datos del formulario
//            int idcuenta = 0;
//            // El valor de la caja de texto se convierte a entero
//            idcuenta = Integer.parseInt(dato.getText());
            verificarNumero();
            verificaVacio();
            
            try {
//                txtSaldo.setText(Double.toString(c1.ConsultaSaldo(idcuenta)));
                txtSaldo.setText(Double.toString(c1.ConsultaSaldo(datoNumerico)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }
        }

        //En caso de que se seleccione el botón CDT
        if (chkSCDT.isSelected()) {
            //1. Recoger los datos de los controles
//            int CDT = Integer.parseInt(dato.getText());
            verificarNumero();
            verificaVacio();
            
            //2. Convertir (si es necesario)
            try {
                //3. Rellenar el filedText del Saldo con el método correspondiente
//                txtSaldo.setText(Double.toString(c1.ConsultaSaldoCDT(CDT)));
                txtSaldo.setText(Double.toString(c1.ConsultaSaldoCDT(datoNumerico)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }
        }

        //En caso de que se seleccione el botón de Saldo Cliente
        if (chkSCliente.isSelected()) {
            //1. Recoger el valor de la caja de texto
           
            String numNIF = dato.getText();
            try {
                //2. LLamar al método correspondiente de saldo de cliente
                txtSaldo.setText(Double.toString(c1.ConsultaSaldoTotal(numNIF)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }

        }
    }//GEN-LAST:event_btnCSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_VariosBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_VariosBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_VariosBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_VariosBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal_VariosBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSaldo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chkSCDT;
    private javax.swing.JRadioButton chkSCliente;
    private javax.swing.JRadioButton chkSCuenta;
    private javax.swing.JTextField dato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblEtiqueta1;
    private javax.swing.JTextArea taMensajeError;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
